repos:
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.1
    hooks:
    -   id: gitlint
- repo: git://github.com/soyoslab/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-lint
    - id: go-imports
    - id: go-cyclo
      args: [-over=15]
    - id: validate-toml
    - id: no-go-testing
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy
