name: log-generator-build
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  ubuntu-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: grab source
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: build
      run: make all
    - name: test
      run: make test
    - name: send coverage
      run: make codacy-coverage-push
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.codacy_project_token }}
  macos-build-and-test:
    runs-on: macos-latest
    steps:
    - name: grab source
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: build
      run: make all
    - name: test
      run: make test
  windows-build-and-test:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - name: grab source
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: build
      run: make all
    - name: test
      run: make test
