name: log-generator-build
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
defaults:
  run:
    shell: bash
jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Grab source
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build
      run: make all
    - name: Test
      run: make test
    - name: Send Coverage
      run: make codacy-coverage-push
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
